### ISSUE TITLE
Issue with opening the 2007 app

### ISSUE THREAD

**Issue by princekitty6243** [CloneTrooper1019/Roblox-2007-Client#10]
Your apps are very good, i really like them, but there is one problem with the 2007 app. when i try to open it, the roblox app says it failed to open the application, because the sie-by-side config was wrong. please help..

**Comment by thatsprettygood** [comment]
I'm having the same problem, when I check the event logs it shows this.

### Activation context generation failed for "C:\Users\mystu\Downloads\Roblox-2007-Client-master\Roblox-2007-Client-master\Roblox.exe". Dependent Assembly

**Comment by BeamV1** [comment]
Having same problem.

**Comment by GlowingUmbreon** [comment]
> Your apps are very good, i really like them, but there is one problem with the 2007 app. when i try to open it, the roblox app says it failed to open the application, because the sie-by-side config was wrong. please help..



> I'm having the same problem, when I check the event logs it shows this.
> 
> ### Activation context generation failed for "C:\Users\user\Downloads\Roblox-2007-Client-master\Roblox-2007-Client-master\Roblox.exe". Dependent Assembly



> Having same problem.

You need to install [Microsoft Visual C++ 2005 Service Pack 1 Redistributable Package x86](https://www.microsoft.com/en-us/download/details.aspx?id=14431#filelist)

**Comment by thatsprettygood** [comment]
that should be added to the readme

> You need to install [Microsoft Visual C++ 2005 Service Pack 1 Redistributable Package x86](https://www.microsoft.com/en-us/download/details.aspx?id=14431#filelist)

**Comment by CloneTrooper1019** [comment]
I’ll look into it, wasn’t aware this was a requirement because I already had it on my PC I guess.

**Comment by CloneTrooper1019** [comment]
Solved this awhile ago. Should be good.
