### ISSUE TITLE
Patching HtmlService in a safe and detectable way

### ISSUE THREAD

**Issue by quinl** [CloneTrooper1019/Roblox-2007-Client#2]
There *is* a stable and detectable way to patch HtmlService on vanilla 2007 clients.
If this is part of the security concern regarding 2007, this might help.

1) Open up the vanilla 2007 client in x64dbg
2) In the top menu bar, click 'View' and click 'Modules'
3) Double click the name of your client executable
4) Right click in the assembly view
5) Go down to 'Search For...' and go to 'Current Module'
6) Click 'String References' and wait for the file to be processed
7) In the 'Search' box, type in 'HtmlService' and double click the first result
8) In the assembly view, scroll up about 4 lines and look for 'jne' without the quotes
9) Switch that to 'jmp' without the quotes
10) In the top menu bar, click 'File' and then click 'Patch File' or press Ctrl-P
11) Make sure your entry is in the 'Patches' list and then click 'Patch File'
12) Save the file as whatever you want to name your client (overwriting it is optional!)
13) Try to create a new window using:
	`game:service'HtmlService':NewWindow()`
14) If it fails, you have successfully patched HtmlService on the client

Testing if clients are using this patch:
* If you're running this in multiplayer:
		- Create a BoolValue named HtmlPatched when a player joins
		- Have a LocalScript run this on the client and report the result back to HtmlPatched
		- If HtmlPatched is false, disconnect/do whatever.

**An example of the script you might use on the client:**
```
local s, f = pcall(function()
	game:GetService("HtmlService"):NewWindow()
end)

if s then
	print("HtmlService is not patched on this client.")
else
	print("HtmlService is patched on this client.")
end
```

A screenshot of these patches and the example above is attached below.
![htmlservice](https://user-images.githubusercontent.com/6856974/33158981-5b9ad88a-cfd4-11e7-8a6b-249daa64eb1d.png)

**Comment by CloneTrooper1019** [comment]
I decided to leave it present in this build as a historical artifact. I already noted in this disclaimer that this build is unpatched, and I’d like to keep this in its vanilla state.
