### ISSUE TITLE
Load model from command roblox.com asset

### ISSUE THREAD

**Issue by RickDoesOn** [CloneTrooper1019/Roblox-2007-Client#4]
Is it possible? If not can you make it to work? Put command

**Comment by P4risAndStuff** [comment]
For now, you can insert models from 2012 and earlier manually. You can get such models from `https://www.roblox.com/asset?ID=[model id]` - for example, https://www.roblox.com/asset?ID=32193128382193891908213132 may download a model in the form of a file with no file name extension. After getting Windows/File Explorer to show file name extensions, you can rename the file and add `.rbxm` to the end, to make it a roblox model file. Then just insert the model into your map.

**Comment by RickDoesOn** [comment]
I did it the same way you did too. https://www.roblox.com/asset?ID=[model id] So I tried to insert a model from 2005!!! THEY WORKS, BUT IF I SAVE THEM AS A FILE AND INSERT IN 2017, IT WORKS TOO! BUT ITS BUGGY.. :-)

**Comment by quinl** [comment]
Yeah, saving the model from 2017 I believe has some kind of different format?
Probably not, I remember seeing it somewhere.

**Comment by CloneTrooper1019** [comment]
@quinl Roblox does have a binary file format now.
