### ISSUE TITLE
didn't work

### ISSUE THREAD

**Issue by ittehgeps** [CloneTrooper1019/Roblox-2007-Client#5]
i went to roblox studio and used the game:Load(stuff) command and it didn't work.
2 starz

**Comment by 1zerozero2** [comment]
Of course, `game:Load(stuff)` doesn't work. It's invalid.

**Comment by quinl** [comment]
`game:Load(url)`

**Comment by ittehgeps** [comment]
@1zerozero2 what i meant is, i used game:Load() and i put the url in and it didn't work. is that better?

**Comment by quinl** [comment]
Some won't load because of the size being too big. Also, you need to use a Roblox place.

**Comment by CloneTrooper1019** [comment]
It has to be a place that is uncopylocked. If you're trying to load in one of your own places, it won't work.
It also has to be a place file encoded in Roblox's XML format.

**Comment by ittehgeps** [comment]
Oh, thanks!
