### ISSUE TITLE
Crashes when opening place

### ISSUE THREAD

**Issue by SMG456** [CloneTrooper1019/Roblox-2007-Client#8]
When I open a place (ROBLOX World Headquarters by Builderman, it's uncopylocked) the game crashes. Look at the attached files.
[log_F9E0C_G3D.txt](https://github.com/CloneTrooper1019/Roblox-2007-Client/files/3341945/log_F9E0C_G3D.txt)
[log_F9E0C_rbx_content_4788.txt](https://github.com/CloneTrooper1019/Roblox-2007-Client/files/3341946/log_F9E0C_rbx_content_4788.txt)
[log_F9E0C.txt](https://github.com/CloneTrooper1019/Roblox-2007-Client/files/3341947/log_F9E0C.txt)

**Comment by CloneTrooper1019** [comment]
I... can’t really do much about this because it’s a closed source exe.
I’ll pass this information along to some folks who might know what’s going on though.

**Comment by SMG456** [comment]
Forgot the minidump. Uploading it.
[log_F9E0C 0, 3, 512, 0.zip](https://github.com/CloneTrooper1019/Roblox-2007-Client/files/3341952/log_F9E0C.0.3.512.0.zip)

**Comment by SMG456** [comment]
> I... can’t really do much about this because it’s a closed source exe.
> I’ll pass this information along to some folks who might know what’s going on though.

I open the place in Roblox Studio 2019 and it works, but the game is broken since most of the scripts have been deleted from the Roblox servers.

**Comment by CloneTrooper1019** [comment]
Is the place file using Roblox’s XML format?

From the exception message its throwing at you, it seems to be a driver issue, but I wouldn’t know anything about diagnosing and fixing that.

Did you extract the exe correctly? Does this happen in other place files, or only this one?

**Comment by SMG456** [comment]
> Does this happen in other place files, or only this one?

Creating a place will also crash the 2007 client.

**Comment by SMG456** [comment]
Apparently it was because I enabled both bloom and depth of field effects. The bloom effect isn't compatible with my system, so Roblox crashes. Closing issue.
